### ISSUE TITLE
Product not added to wishlist

### ISSUE THREAD

**Issue by aimeric** [webburza/sylius-wishlist-bundle#14]
@ychanan ychanan , @dkarlovi 

Hi,

I have include as explained in the documentation the add to wishlist button under the add to cart button. But when I click on the button add to wishlist I get redirect to the cart page and no product is added to the wishlist.

I have insert this line into  **_addToCart.html.twig**
{% include '@WebburzaSyliusWishlist/Frontend/Shop/_addToWishlist.html.twig' %}

**src/app/config/routing.yml**

```
webburza_wishlist:
    resource: "@WebburzaSyliusWishlistBundle/Resources/config/routing.yml"

webburza_wishlist_front:
    resource: "@WebburzaSyliusWishlistBundle/Resources/config/routingFront.yml"
    prefix: /wishlist

webburza_wishlist_account:
    resource: "@WebburzaSyliusWishlistBundle/Resources/config/routingAccount.yml"
    prefix: /account/wishlists
```
src/app/config/config.yml
```
imports:
    - { resource: "@WebburzaSyliusWishlistBundle/Resources/config/config.yml" }
webburza_sylius_wishlist:
    multiple: true           # multiple wishlist mode
    default_public: false    # used for automatically created wishlists
```
Sylius version : 1.0.0-beta.3

Any help please.
